### ISSUE TITLE
Where is the image assets used in this book?

### ISSUE THREAD

**Issue by notalentgeek** [PacktPublishing/Unity-2017-2D-Game-Development-Projects#1]
The book said that the image asset can be downloaded here ---> [http://player26.com/product/anglecakes](http://player26.com/product/anglecakes) but it is a dead link. Where I can download the assets?

Reference ---> [https://subscription.packtpub.com/book/game_development/9781786460271/2/ch02lvl1sec24/setting-up-the-angel-cakes-project](https://subscription.packtpub.com/book/game_development/9781786460271/2/ch02lvl1sec24/setting-up-the-angel-cakes-project)

![https://i.imgur.com/IxJgfII.png](https://i.imgur.com/IxJgfII.png)

**Comment by AurobindoKar** [comment]
Hello,
You can find the files at this link:  https://drive.google.com/drive/folders/1tG6llACozS_mE-jCzc1krcNfII3c2ZeC?usp=sharing
The site has been down for some time due to technical reasons, and we are working to restore it.
Regards,
Packt
